service: vehicleCrud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  environment:
    DYNAMODB_VEHICLE_TABLE: ${self:service}-vehicleTable-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-vehicleTable-${sls:stage}

functions:
  getVehicle:
    handler: index.getVehicleHandler
    events:
      - httpApi:
          path: /
          method: post
  postVehicle:
    handler: index.postVehicleHandler
    events:
      - httpApi:
          path: /create
          method: post
	
resources:
  Resources:
    VehicleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: reg
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: reg
            KeyType: HASH
        TableName: ${self:service}-vehicleTable-${sls:stage}