service: vehicleCrud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: default

  environment:
    DYNAMODB_VEHICLE_TABLE: ${self:service}-vehicleTable-${sls:stage}

functions:
  getVehicle:
    handler: index.getVehicleHandler
    events:
      - httpApi:
          path: /
          method: get
  postVehicle:
    handler: index.postVehicleHandler
    events:
      - httpApi:
          path: /
          method: post
	
resources:
  Resources:
    VehicleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: reg
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: reg
            KeyType: HASH
        TableName: ${self:service}-vehicleTable-${sls:stage}