service: vehicleCrud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: default

functions:
  getVehicle:
    handler: index.getVehicleHandler
    events:
      - httpApi:
          path: /
          method: get
  postVehicle:
    handler: index.postVehicleHandler
    events:
      - httpApi:
          path: /
          method: post
